#if defined(CHALLENGE_BYPASS_RISTRETTO_SHARED_LIBRARY)
#if defined(WIN32)
#if defined(CHALLENGE_BYPASS_RISTRETTO_IMPLEMENTATION)
#define CHALLENGE_BYPASS_RISTRETTO_EXPORT __declspec(dllexport)
#else
#define CHALLENGE_BYPASS_RISTRETTO_EXPORT __declspec(dllimport)
#endif  // defined(CHALLENGE_BYPASS_RISTRETTO_IMPLEMENTATION)
#else  // defined(WIN32)
#if defined(CHALLENGE_BYPASS_RISTRETTO_IMPLEMENTATION)
#define CHALLENGE_BYPASS_RISTRETTO_EXPORT __attribute__((visibility("default")))
#else
#define CHALLENGE_BYPASS_RISTRETTO_EXPORT
#endif
#endif
#else // defined(CHALLENGE_BYPASS_RISTRETTO_SHARED_LIBRARY)
#define CHALLENGE_BYPASS_RISTRETTO_EXPORT
#endif
